server:
  port:
    9380

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

spring:
  application:
    name: EMAIL

  output:
    ansi:
      enabled: ALWAYS

  mail:
    host: smtp.gmail.com
    port: 587
    username: valetbyte22@gmail.com
    password: "gilykyftbbdpktsd"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: valetbyte22@gmail.com
      text: Valet Byte